# Generated by Django 3.1 on 2021-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_stripecustomerintent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomerintent',
            name='cancel_payment_intent',
            field=models.TextField(default=''),
        ),
    ]
