# Generated by Django 3.1 on 2021-08-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0039_auto_20210825_1836'),
        ('payments', '0005_stripecustomerintent_cancel_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomerintent',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.shoporder'),
        ),
    ]
