# Generated by Django 3.1 on 2021-09-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_stripeorderpaymentintent_create_ephemeral_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeorderpaymentintent',
            name='create_payment_intent_client_secret',
            field=models.TextField(default=''),
        ),
    ]
