# Generated by Django 3.1 on 2021-09-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20210902_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverearning',
            name='tip',
            field=models.FloatField(default=0.0),
        ),
    ]
