# Generated by Django 3.0.4 on 2021-03-17 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authModule', '0006_auto_20210316_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_column='title', default='')),
                ('description', models.TextField(db_column='description', default='')),
                ('price', models.IntegerField(db_column='price', default=0)),
                ('sale_price', models.IntegerField(db_column='sale_price', default=0)),
                ('is_active', models.BooleanField(db_column='is_active', default=False)),
                ('sku', models.TextField(db_column='sku', default='')),
                ('barcode', models.TextField(db_column='barcode', default='')),
                ('quantity', models.IntegerField(db_column='quantity', default=0)),
                ('weight', models.FloatField(db_column='weight', default='')),
                ('weight_unit', models.TextField(db_column='weight_unit', default='')),
                ('tags', models.TextField(db_column='tags', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('seller', models.ForeignKey(db_column='seller', on_delete=django.db.models.deletion.CASCADE, to='authModule.Seller')),
                ('shop', models.ForeignKey(db_column='shop', on_delete=django.db.models.deletion.CASCADE, to='authModule.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', default='')),
                ('shop_product', models.ForeignKey(db_column='shop_product', on_delete=django.db.models.deletion.CASCADE, to='seller.Shop_Product')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(db_column='full_name', default='')),
                ('email_address', models.TextField(db_column='email_address', default='')),
                ('phone_number', models.TextField(db_column='phone_number', default='')),
                ('company', models.TextField(db_column='company', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Product_Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', default='')),
                ('value', models.TextField(db_column='value', default='')),
                ('price', models.IntegerField(db_column='price', default=0)),
                ('sale_price', models.IntegerField(db_column='sale_price', default=0)),
                ('sku', models.TextField(db_column='sku', default='')),
                ('quantity', models.IntegerField(db_column='quantity', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('shop_product', models.ForeignKey(db_column='shop_product', on_delete=django.db.models.deletion.CASCADE, to='seller.Shop_Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', default='')),
                ('shop_product_category', models.ForeignKey(db_column='shop_product_category', on_delete=django.db.models.deletion.CASCADE, to='seller.Shop_Product_Category')),
            ],
        ),
        migrations.AddField(
            model_name='shop_product',
            name='vendor',
            field=models.ForeignKey(db_column='vendor', on_delete=django.db.models.deletion.CASCADE, to='seller.Vendor'),
        ),
    ]
