# Generated by Django 3.0.4 on 2021-03-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0006_auto_20210316_1727'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shop',
            field=models.ForeignKey(db_column='shop', null=True, on_delete=django.db.models.deletion.CASCADE, to='authModule.Shop'),
        ),
    ]
