# Generated by Django 3.0.4 on 2021-03-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_vendor_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_product_variant',
            name='barcode',
            field=models.TextField(db_column='barcode', default=''),
        ),
    ]
