# Generated by Django 3.0.4 on 2021-03-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_shop_product_variant_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Product_Variant_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.TextField(db_column='image_link', default='')),
                ('shop_product_variant', models.ForeignKey(db_column='shop_product_variant', on_delete=django.db.models.deletion.CASCADE, to='seller.Shop_Product_Variant')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Product_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.TextField(db_column='image_link', default='')),
                ('shop_product', models.ForeignKey(db_column='shop_product', on_delete=django.db.models.deletion.CASCADE, to='seller.Shop_Product')),
            ],
        ),
    ]
