# Generated by Django 3.0.4 on 2021-03-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0006_auto_20210316_1727'),
        ('seller', '0004_shop_product_images_shop_product_variant_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Product_Variant_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.TextField(db_column='option_name', default='')),
                ('seller', models.ForeignKey(db_column='seller', on_delete=django.db.models.deletion.CASCADE, to='authModule.Seller')),
                ('shop', models.ForeignKey(db_column='shop', on_delete=django.db.models.deletion.CASCADE, to='authModule.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='shop_Product_Variant_Option_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.TextField(db_column='option_value', default='')),
                ('shop_product_variant_option', models.ForeignKey(db_column='shop_product_variant_option', on_delete=django.db.models.deletion.CASCADE, to='seller.Shop_Product_Variant_Option')),
            ],
        ),
    ]
