# Generated by Django 3.0.4 on 2021-03-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0007_auto_20210327_1417'),
        ('seller', '0005_shop_product_variant_option_shop_product_variant_option_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shop',
            field=models.ForeignKey(blank=True, db_column='shop', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authModule.Shop'),
        ),
    ]
