# Generated by Django 3.0.4 on 2021-03-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_auto_20210329_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_product_category',
            name='shop_product',
            field=models.ForeignKey(db_column='shop_product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.Shop_Product'),
        ),
        migrations.AlterField(
            model_name='shop_product_type',
            name='shop_product_category',
            field=models.ForeignKey(db_column='shop_product_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.Shop_Product_Category'),
        ),
    ]
