# Generated by Django 3.1 on 2021-06-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0023_card_details_user_addresses'),
        ('seller', '0013_auto_20210602_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('sku', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField()),
                ('weight_unit', models.CharField(max_length=20)),
                ('tags', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propane_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propane_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('propane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.propane')),
            ],
        ),
        migrations.AddField(
            model_name='propane',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.propane_company'),
        ),
        migrations.AddField(
            model_name='propane',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.seller'),
        ),
        migrations.AddField(
            model_name='propane',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.shop'),
        ),
    ]
