# Generated by Django 3.1 on 2021-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20210610_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propane',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propane',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propane',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
