# Generated by Django 3.1 on 2021-06-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0031_auto_20210625_0545'),
        ('seller', '0020_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authModule.user_addresses'),
        ),
    ]
