# Generated by Django 3.1 on 2021-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_auto_20210626_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
