# Generated by Django 3.1 on 2021-06-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0023_auto_20210629_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
