# Generated by Django 3.1 on 2021-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0024_auto_20210630_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
