# Generated by Django 3.1 on 2021-07-01 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0033_auto_20210626_1430'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0025_auto_20210630_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignOrderToDriverForAcceptence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.driver')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.shop')),
            ],
        ),
    ]
