# Generated by Django 3.1 on 2021-07-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0026_auto_20210630_1723'),
        ('seller', '0026_assignordertodriverforacceptence'),
    ]

    operations = [
    ]
