# Generated by Django 3.1 on 2021-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0027_merge_20210702_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignordertodriverforacceptence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='assignordertodriverforacceptence',
            name='is_order_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
