# Generated by Django 3.1 on 2021-07-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0029_assignordertodriverforacceptence_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignordertodriverforacceptence',
            name='order',
        ),
        migrations.CreateModel(
            name='AssignOrderListToDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.assignordertodriverforacceptence')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.order')),
            ],
        ),
    ]
