# Generated by Django 3.1 on 2021-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0031_auto_20210729_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_product',
            name='price',
            field=models.FloatField(db_column='price', default=0),
        ),
        migrations.AlterField(
            model_name='shop_product',
            name='sale_price',
            field=models.FloatField(db_column='sale_price', default=0),
        ),
    ]
