# Generated by Django 3.1 on 2021-08-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0032_auto_20210729_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
