# Generated by Django 3.1 on 2021-08-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0034_auto_20210809_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propane',
            name='propane_category',
            field=models.CharField(default='', max_length=8),
        ),
    ]
