# Generated by Django 3.1 on 2021-08-11 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0036_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropaneReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_in_star', models.FloatField()),
                ('review_in_text', models.TextField(default='')),
                ('propane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.propane')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
