# Generated by Django 3.1 on 2021-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0037_propanereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_procced',
            field=models.BooleanField(default=False),
        ),
    ]
