# Generated by Django 3.1 on 2021-08-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0040_driver_review_in_star'),
        ('seller', '0038_order_is_payment_procced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0)),
                ('sub_total_amount', models.FloatField(default=0)),
                ('is_driver_accepted', models.BooleanField(default=False)),
                ('is_shop_accepted', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='', max_length=10)),
                ('cancelled_by', models.CharField(default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authModule.driver')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.shop')),
            ],
        ),
        migrations.AlterField(
            model_name='assignorderlisttodriver',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.shoporder'),
        ),
        migrations.AlterField(
            model_name='delivery_scheduling',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.shoporder'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.shoporder'),
        ),
    ]
