# Generated by Django 3.1 on 2021-08-25 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0040_driver_review_in_star'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0040_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporder',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee', models.FloatField(default=0)),
                ('delivery_fee', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('is_payment_procced', models.BooleanField(default=False)),
                ('order_status', models.CharField(default='', max_length=10)),
                ('is_shops_accepted', models.BooleanField(default=False)),
                ('is_drivers_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.delivery_options')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authModule.user_addresses')),
            ],
        ),
        migrations.AddField(
            model_name='shoporder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.order'),
        ),
    ]
