# Generated by Django 3.1 on 2021-08-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0041_auto_20210825_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_scheduling',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.order'),
        ),
    ]
