# Generated by Django 3.1 on 2021-08-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0042_auto_20210825_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignordertodriverforacceptence',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='assignordertodriverforacceptence',
            name='shop',
        ),
        migrations.AddField(
            model_name='assignordertodriverforacceptence',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.order'),
        ),
    ]
