# Generated by Django 3.1 on 2021-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0043_auto_20210827_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignordertodriverforacceptence',
            name='is_order_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
