# Generated by Django 3.1 on 2021-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0044_auto_20210827_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignordertodriverforacceptence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
