# Generated by Django 3.1 on 2021-08-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0049_auto_20210831_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_anonymous_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propanereview',
            name='is_anonymous_review',
            field=models.BooleanField(default=False),
        ),
    ]
