# Generated by Django 3.1 on 2021-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0050_auto_20210831_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='is_shop_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
