# Generated by Django 3.1 on 2021-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0051_auto_20210901_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='item_status',
            field=models.CharField(default='To-do', max_length=20),
        ),
    ]
