# Generated by Django 3.1 on 2021-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0054_auto_20210903_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver_accepted_time',
            field=models.DateTimeField(),
        ),
    ]
