# Generated by Django 3.1 on 2021-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0057_auto_20210903_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='accepted', max_length=20),
        ),
    ]
