# Generated by Django 3.1 on 2021-09-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0058_auto_20210906_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bogo', models.CharField(max_length=100)),
                ('secret_code', models.TextField()),
                ('discount_in_percentage', models.FloatField()),
                ('expiry_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
        ),
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='propanereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True),
        ),
    ]
