# Generated by Django 3.1 on 2021-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0059_auto_20210910_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='descriptions',
            field=models.TextField(default=''),
        ),
    ]
