# Generated by Django 3.1 on 2021-09-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0060_coupon_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='propane_state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
