# Generated by Django 3.0.4 on 2021-03-12 14:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_security_number', models.TextField(db_column='social_security_number', default='')),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.TextField(db_column='vehicle_type', default='')),
                ('vehicle_make', models.TextField(db_column='vehicle_make', default='')),
                ('vehicle_number', models.TextField(db_column='vehicle_number', default='')),
                ('vehicle_color', models.TextField(db_column='vehicle_color', default='')),
                ('driver', models.ForeignKey(db_column='driver', null=True, on_delete=django.db.models.deletion.CASCADE, to='authModule.Driver')),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('role', models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='utilities.Role')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserRole',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', default='')),
                ('address', models.TextField(db_column='address', default='')),
                ('phone_number', models.TextField(db_column='phone_number', default='')),
                ('date_of_birth', models.CharField(db_column='date_of_birth', default='', max_length=15)),
                ('is_seller', models.BooleanField(db_column='is_seller', default=False)),
                ('is_buyer', models.BooleanField(db_column='is_buyer', default=False)),
                ('is_driver', models.BooleanField(db_column='is_driver', default=False)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='ShopHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TextField(db_column='open_time', default='')),
                ('close_time', models.TextField(db_column='close_time', default='')),
                ('is_always_open', models.BooleanField(db_column='is_always_open', default=False)),
                ('seller', models.ForeignKey(db_column='seller', on_delete=django.db.models.deletion.CASCADE, to='authModule.Seller')),
            ],
            options={
                'db_table': 'ShopHour',
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='profile',
            field=models.OneToOneField(db_column='profile', on_delete=django.db.models.deletion.CASCADE, to='authModule.UserProfile'),
        ),
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='authModule.UserRole'),
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(db_column='verification_code', default='', max_length=6)),
                ('key_expires', models.DateTimeField(db_column='key_expires', default=datetime.datetime.now)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ResetPassword',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_state', models.TextField(db_column='license_state', default='')),
                ('license_number', models.TextField(db_column='license_number', default='')),
                ('license_exp_date', models.TextField(db_column='license_exp_date', default='')),
                ('driver', models.ForeignKey(db_column='driver', null=True, on_delete=django.db.models.deletion.CASCADE, to='authModule.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='profile',
            field=models.ForeignKey(db_column='profile', on_delete=django.db.models.deletion.CASCADE, to='authModule.UserProfile'),
        ),
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='authModule.UserRole'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bank_card_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_card', models.CharField(db_column='name_of_card', default='', max_length=30)),
                ('card_number', models.CharField(db_column='card_number', default='', max_length=30)),
                ('expiry_date', models.CharField(db_column='expiry_date', default='', max_length=30)),
                ('cvv_number', models.CharField(db_column='cvv_number', default='', max_length=3)),
                ('billing_address', models.TextField(db_column='billing_address', default='')),
                ('is_save', models.BooleanField(db_column='is_save', default=False)),
                ('driver', models.ForeignKey(db_column='driver', null=True, on_delete=django.db.models.deletion.CASCADE, to='authModule.Driver')),
            ],
            options={
                'db_table': 'Bank_card_details',
            },
        ),
    ]
