# Generated by Django 3.0.4 on 2021-03-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0002_auto_20210313_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopHour',
            new_name='Shop',
        ),
    ]
