# Generated by Django 3.0.4 on 2021-03-13 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authModule', '0003_auto_20210313_1017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resetpassword',
            table=None,
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_column='phone_number', default='', max_length=30)),
                ('verification_code', models.CharField(db_column='verification_code', default='', max_length=6)),
                ('key_expires', models.DateTimeField(db_column='key_expires', default=datetime.datetime.now)),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ResetPassword',
            },
        ),
    ]
