# Generated by Django 3.0.4 on 2021-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0004_auto_20210313_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.TextField(db_column='lat', default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.TextField(db_column='lng', default=''),
        ),
    ]
