# Generated by Django 3.0.4 on 2021-03-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0005_auto_20210316_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='lat',
            field=models.TextField(db_column='lat', default=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='lng',
            field=models.TextField(db_column='lng', default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.TextField(db_column='lat', default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.TextField(db_column='lng', default=''),
        ),
    ]
