# Generated by Django 3.0.4 on 2021-03-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0006_auto_20210316_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumbers',
            name='user',
        ),
        migrations.AlterModelTable(
            name='phonenumbers',
            table='PhoneNumbers',
        ),
    ]
