# Generated by Django 3.0.4 on 2021-03-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0007_auto_20210327_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.TextField(db_column='phone_number', default=''),
        ),
    ]
