# Generated by Django 3.1 on 2021-04-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0008_shop_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.TextField(db_column='profile_image_url', default=''),
        ),
        migrations.CreateModel(
            name='Shop_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_image_url', models.TextField(db_column='shop_image_url', default='')),
                ('shop', models.ForeignKey(db_column='shop', on_delete=django.db.models.deletion.CASCADE, to='authModule.shop')),
            ],
        ),
    ]
