# Generated by Django 3.1 on 2021-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0009_auto_20210426_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='week',
            field=models.JSONField(null=True),
        ),
    ]
