# Generated by Django 3.1 on 2021-05-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0010_shop_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_verified_from_checker',
            field=models.BooleanField(db_column='is_verified', default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(db_column='first_name', default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.TextField(db_column='last_name', default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.TextField(db_column='middle_name', default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.TextField(db_column='zip_code', default=''),
        ),
        migrations.CreateModel(
            name='Driver_checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker_driver_id', models.TextField(db_column='checker_driver_id', default='')),
                ('checker_report_id', models.TextField(db_column='checker_report_id', default='')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authModule.driver')),
            ],
        ),
    ]
