# Generated by Django 3.1 on 2021-05-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0011_auto_20210528_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='open_time',
        ),
    ]
