# Generated by Django 3.1 on 2021-05-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0012_auto_20210528_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerShopHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(db_column='day', default='')),
            ],
            options={
                'db_table': 'SellerShopHour',
            },
        ),
        migrations.AlterModelTable(
            name='shop',
            table='Shop',
        ),
        migrations.CreateModel(
            name='ShopHourTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open_24', models.BooleanField(default=False)),
                ('is_close', models.BooleanField(default=False)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.sellershophour')),
            ],
            options={
                'db_table': 'ShopHourTiming',
            },
        ),
        migrations.AddField(
            model_name='sellershophour',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.shop'),
        ),
    ]
