# Generated by Django 3.1 on 2021-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0013_auto_20210530_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shophourtiming',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shophourtiming',
            name='open_time',
            field=models.TimeField(null=True),
        ),
    ]
