# Generated by Django 3.1 on 2021-05-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0014_auto_20210530_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRadiusSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_location', models.BooleanField(default=False)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authModule.driver')),
            ],
        ),
    ]
