# Generated by Django 3.1 on 2021-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0017_auto_20210602_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='auto_insurance_expiry',
            field=models.DateField(auto_now_add=True, db_column='auto_insurance_expiry', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='auto_insurance_number',
            field=models.TextField(db_column='auto_insurance_number', default=''),
        ),
    ]
