# Generated by Django 3.1 on 2021-06-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0019_auto_20210602_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='auto_insurance_expiry',
            field=models.DateField(blank=True, db_column='auto_insurance_expiry', null=True),
        ),
    ]
