# Generated by Django 3.1 on 2021-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0020_auto_20210602_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=False),
        ),
    ]
