# Generated by Django 3.1 on 2021-06-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0023_card_details_user_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
