# Generated by Django 3.1 on 2021-06-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0024_driver_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_addresses',
            name='lat',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user_addresses',
            name='lng',
            field=models.CharField(default='', max_length=30),
        ),
    ]
