# Generated by Django 3.1 on 2021-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0025_auto_20210615_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverradiussettings',
            name='radius',
            field=models.FloatField(default=0),
        ),
    ]
