# Generated by Django 3.1 on 2021-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0028_auto_20210622_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_addresses',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
