# Generated by Django 3.1 on 2021-06-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_kwkusecase_code'),
        ('authModule', '0029_user_addresses_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active_taxi_and_delivery_role',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DriverRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authModule.driver')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.role')),
            ],
        ),
    ]
