# Generated by Django 3.1 on 2021-06-26 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authModule', '0031_auto_20210625_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_card_detail',
            name='driver',
        ),
        migrations.AddField(
            model_name='bank_card_detail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
