# Generated by Django 3.1 on 2021-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0032_auto_20210626_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_addresses',
            name='bussines_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_addresses',
            name='delivery_instruction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_addresses',
            name='appartment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
