# Generated by Django 3.1 on 2021-07-08 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0033_auto_20210626_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50)),
                ('verification_code', models.CharField(db_column='verification_code', default='', max_length=6)),
                ('key_expires', models.DateTimeField(db_column='key_expires', default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
            ],
        ),
    ]
