# Generated by Django 3.1 on 2021-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0034_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.TextField(default=''),
        ),
    ]
