# Generated by Django 3.1 on 2021-08-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0036_auto_20210712_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='strip_customer_key',
            field=models.TextField(default=''),
        ),
    ]
