# Generated by Django 3.1 on 2021-08-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0037_userprofile_strip_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_addresses',
            name='title',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
