# Generated by Django 3.1 on 2021-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0038_auto_20210811_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='review_in_star',
            field=models.FloatField(default=5.0),
        ),
    ]
