# Generated by Django 3.1 on 2021-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0039_shop_review_in_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='review_in_star',
            field=models.FloatField(default=5.0),
        ),
    ]
