# Generated by Django 3.1 on 2021-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0040_driver_review_in_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
