# Generated by Django 3.1 on 2021-09-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0041_shop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverroles',
            name='role',
        ),
        migrations.AddField(
            model_name='driverroles',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
