# Generated by Django 3.1 on 2021-09-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0042_auto_20210916_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverradiussettings',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driverradiussettings',
            name='longitude',
        ),
        migrations.AddField(
            model_name='driverradiussettings',
            name='lat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driverradiussettings',
            name='lng',
            field=models.CharField(default='', max_length=255),
        ),
    ]
