# Generated by Django 3.1 on 2021-09-24 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authModule', '0043_auto_20210921_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=255)),
                ('account_object', models.CharField(max_length=255)),
                ('holder_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('routing_number', models.CharField(max_length=255)),
                ('stripe_source_key', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='card_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bank_card_detail',
        ),
        migrations.DeleteModel(
            name='Card_Details',
        ),
    ]
