# Generated by Django 3.1 on 2021-09-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0045_bankaccountdetails_is_bank_account_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdetails',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
