# Generated by Django 3.0.4 on 2021-04-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0012_auto_20210329_1531'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authModule', '0008_shop_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='quantity', default=0)),
                ('product', models.ForeignKey(db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Shop_Product')),
                ('shop', models.ForeignKey(db_column='shop', null=True, on_delete=django.db.models.deletion.CASCADE, to='authModule.Shop')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
