# Generated by Django 3.1 on 2021-06-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_auto_20210609_0840'),
        ('buyer', '0002_add_to_cart_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_to_cart',
            old_name='quantity',
            new_name='product_quantity',
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='propane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.propane'),
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='propane_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
