# Generated by Django 3.1 on 2021-09-13 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0060_coupon_descriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer', '0003_auto_20210609_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAppliedCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.order')),
            ],
        ),
    ]
