# Generated by Django 3.1 on 2021-05-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_temp_product_barcode_scanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='USState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', default='')),
                ('abbr', models.TextField(db_column='abbr', default='')),
            ],
        ),
    ]
