# Generated by Django 3.1 on 2021-06-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_auto_20210602_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='KwkUsecase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KwkCartConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_value', models.FloatField(blank=True, null=True)),
                ('discount_value', models.FloatField(blank=True, null=True)),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.kwkusecase')),
            ],
        ),
    ]
