# Generated by Django 3.1 on 2021-06-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_kwkcartconfigurations_kwkusecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwkusecase',
            name='code',
            field=models.CharField(default='', max_length=15),
        ),
    ]
